import assert from 'assert';
import { applyHomeyPopupValues, filterPopupFlowValues } from '../lib/panel/value-sources';
import { createFanState, createSelectState, createLightState, createShutterState, createThermoState } from '../lib/panel/state-defaults';

const data: Record<string, unknown> = {onoff:false,dim:0,light_temperature:0.4,light_hue:0.7,light_saturation:0.8,windowcoverings_set:0,windowcoverings_tilt_set:0.2,thermostat_mode:'HeatMode',custom_mode:'AwayMode'};
const source = {bound:true,capabilityId:'custom_mode',read:(id:string)=>data[id]};
const light=createLightState({onoff:true,brightness:80,color:'red'});
applyHomeyPopupValues('light',light,source);
assert.equal(light.onoff,false);assert.equal(light.brightness,0);assert.equal(light.colorTemp,40);assert.equal(light.hue,0.7);assert.equal(light.color,'red');
const prior={...light};data.dim=NaN;data.light_temperature=Infinity;data.onoff=null;data.light_hue=undefined;
applyHomeyPopupValues('light',light,source);assert.deepEqual(light,prior,'Invalid or unavailable values retain the last display state');
const fan=createFanState({maxSpeed:8});data.dim=0.5;
applyHomeyPopupValues('fan',fan,source);assert.equal(fan.speed,4);
const shutter=createShutterState();applyHomeyPopupValues('shutter',shutter,source);assert.equal(shutter.position,0);assert.equal(shutter.tilt,20);
const selector=createSelectState();applyHomeyPopupValues('select',selector,source);assert.equal(selector.currentMode,'AwayMode');
data.custom_mode=null;applyHomeyPopupValues('select',selector,source);assert.equal(selector.currentMode,'AwayMode');
const thermo=createThermoState({currentMode2:'Oma esiasetus'});applyHomeyPopupValues('thermo',thermo,source);
assert.equal(thermo.currentMode1,'HeatMode');assert.equal(thermo.currentMode2,'Oma esiasetus');
applyHomeyPopupValues('light',light,{bound:false,read:()=>{throw new Error('Flow sources must not read Homey');}});
const supplied={onoff:true,brightness:15,color_temp:25,hue:0.1,saturation:0.2,color:'blue',label:'Oma otsikko'};
const filtered=filterPopupFlowValues('light',supplied,true);
assert.deepEqual(filtered,{color:'blue',label:'Oma otsikko'});assert.equal(supplied.brightness,15,'Filtering does not mutate Flow input');
assert.strictEqual(filterPopupFlowValues('light',supplied,false),supplied);
assert.deepEqual(filterPopupFlowValues('fan',{onoff:false,speed:3,mode:'Tehostus'},true),{mode:'Tehostus'});
assert.deepEqual(filterPopupFlowValues('shutter',{position:20,tilt:10,hasTilt:false,label:'Verho'},true),{label:'Verho'});
assert.deepEqual(filterPopupFlowValues('select',{current:'x',mode:'y',title:'Tila'},true),{title:'Tila'});
assert.deepEqual(filterPopupFlowValues('thermo',{mode1:'off',mode:'heat',mode2:'boost'},true,true),{mode2:'boost'});
assert.equal(filterPopupFlowValues('thermo',{mode_row:'mode2',mode:'boost'},true,true).mode,'boost');
assert.equal(filterPopupFlowValues('thermo',{mode:'heat'},true,false).mode,'heat','Thermostat without mode capability keeps Flow mode support');
console.log('Value sources: Homey precedence, Flow metadata, zero/false, invalid/missing readings and secondary thermostat modes passed');
